source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

target "PersonalityTest" do
    pod 'SnapKit'

    target "PersonalityTestTests" do
        inherit! :complete
    end
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
    end
end
